// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHqOZZU-9Hklp9K-pk3MeU5WLV3frI5wU',
    appId: '1:894983013536:web:5b9cad54325d10e80f35c5',
    messagingSenderId: '894983013536',
    
    // --- BAGIAN INI SUDAH DIPERBARUI ---
    projectId: 'sync-task-app-7c0b0', 
    authDomain: 'sync-task-app-7c0b0.firebaseapp.com',
    storageBucket: 'sync-task-app-7c0b0.firebasestorage.app',
    // -----------------------------------
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Xb18Htr77qz34dlL_kNcF-_1LQ6n-mM',
    appId: '1:894983013536:android:e1d297af7973dd200f35c5',
    messagingSenderId: '894983013536',
    
    // --- BAGIAN INI SUDAH DIPERBARUI ---
    projectId: 'sync-task-app-7c0b0',
    storageBucket: 'sync-task-app-7c0b0.firebasestorage.app',
    // -----------------------------------
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3ms5e3rQ1ElvtiT0aswK3Ccc4dV-dzs',
    appId: '1:894983013536:ios:35f382b4decd6f2d0f35c5',
    messagingSenderId: '894983013536',
    
    // --- BAGIAN INI SUDAH DIPERBARUI ---
    projectId: 'sync-task-app-7c0b0',
    storageBucket: 'sync-task-app-7c0b0.firebasestorage.app',
    // -----------------------------------
    iosBundleId: 'com.example.syncTaskApp',
  );
}